/** Generated by tooling/generate-arc-runtime-pins.mjs; compile Arc before checking. */
export const ARC_REVIEWED_V2_RUNTIMES = {
  "swap": {
    "contract": "KletiaArcSwapV2",
    "runtimeCodehash": "0xe37cf3a81234d0d30d1b6545d66bbc69e02c07176438916ee0ea9c4a4ff8bd6c",
    "runtimeBytes": 13965
  },
  "staking": {
    "contract": "KletiaArcStakingV2",
    "runtimeCodehash": "0xf96b14aa8aba96739d6890fc77360ec4cc1f06deea62951a67c7d95c2c82b375",
    "runtimeBytes": 9699
  },
  "lending": {
    "contract": "KletiaArcLendingV2",
    "runtimeCodehash": "0x4ff42e9dd7db4b0d2dafd6deeba3094aec6bd8fa46c59f40b0e12e508fb6601b",
    "runtimeBytes": 14568
  }
} as const;

export const ARC_REVIEWED_FORWARDER = "0x7dE7A249673F2235A91E484CfCE49D00867B67Ec";
export const ARC_REVIEWED_TOKEN = "0xAe77D247c26258397653a020995E957Bc88E039A";
