const fs = require('fs');
const path = require('path');

const dir = './src';

const replacements = {
  "İmza Talebi Oluşturuluyor (Gasless)": "Signature Request Creating (Gasless)",
  "Nonce alınamadı": "Could not fetch nonce",
  "Lütfen Confirmyın": "Please Confirm",
  "Relay başarısız": "Relay failed",
  "MANTIK BLOKLARI (MOTOR AYNI ŞEKİLDE ÇALIŞIYOR)": "LOGIC BLOCKS (ENGINE WORKS THE SAME)",
  "Lütfen önce sağ üstten cüzdanını bağla dostum.": "Please connect your wallet from the top right first, buddy.",
  "Network taranıyor...": "Scanning network...",
  "Ajan Errorsı": "Agent Error",
  "Ajan işlemleri başlatıyor": "Agent is starting operations",
  "Ajan moduna geçildi": "Switched to Agent mode",
  "Ajan düşünüyor/cevaplıyor": "Agent is thinking/replying",
  "Araç Çalıştı": "Tool Executed",
  "Görev sonlandı": "Task completed",
  "İşlem Cancel": "Transaction Cancelled",
  "İzin kontrol ediliyor": "Checking permission",
  "İzin eksik. Lütfen MetaMask üzerinden onay verin.": "Missing permission. Please approve via MetaMask.",
  "İzin ağa gönderildi. Onay bekleniyor...": "Permission sent to network. Waiting for confirmation...",
  "İzin onaylandı. Senkronizasyon (3 sn)...": "Permission approved. Syncing (3 sec)...",
  "Native ETH tespit edildi. İzin (Approve) atlandı.": "Native ETH detected. Approve skipped.",
  "İŞLEM SİMÜLASYONU (Dry Run) BAŞLATILIYOR": "STARTING TRANSACTION SIMULATION (Dry Run)",
  "Simulation Successful! Kontrat işlemi onayladı.": "Simulation Successful! Contract approved transaction.",
  "İşlem Networkda! Hash:": "Transaction on Network! Hash:",
  "Onay bekleniyor": "Waiting for confirmation",
  "BAŞARILI! Kletia görevini tamamladı.": "SUCCESS! Kletia completed its task.",
  "İŞLEM AĞDA BAŞARISIZ OLDU.": "TRANSACTION FAILED ON NETWORK.",
  "BAŞARILI (Sponsorlu Gasless)!": "SUCCESS (Sponsored Gasless)!",
  "ARAYÜZ (UI) - KUSURSUZ MOBİL UYUM & NEOBRUTALISM MATRIX": "UI - FLAWLESS MOBILE SUPPORT & NEOBRUTALISM MATRIX",
  "GEOMETRİK KARMAŞA (NeoBrutalism Grid ve Şekiller)": "GEOMETRIC CHAOS (NeoBrutalism Grid and Shapes)",
  "Mühendislik Kağıdı Noktaları": "Engineering Paper Dots",
  "Mobil Uyumlu Büyük Tipografi": "Mobile Friendly Large Typography",
  "Sol Menü (App Hub)": "Left Menu (App Hub)",
  "MESAJ BALONU: Ekrandan taşmaması için break-words eklendi": "MESSAGE BUBBLE: Added break-words to prevent overflow",
  "ROTA SEÇİCİ VE ONAY BUTONU": "ROUTE SELECTOR AND CONFIRM BUTTON",
  "Veri çekilemedi.": "Could not fetch data.",
  "Connecttı hatası.": "Connection error.",
  "Canlı Fiyat &gt; AI Tahmini ➔ Otomatik Karar": "Live Price &gt; AI Prediction ➔ Auto Decision",
  "ZAMAN DİLİMİ SEÇİMİ": "TIMEFRAME SELECTION",
  "5 Dakika (Kısa Vade)": "5 Minutes (Short Term)",
  "Piyasa Analizi Yapılıyor...": "Market Analysis in Progress...",
  "Anlık Fiyat (Binance)": "Live Price (Binance)",
  "Allora'nın yükseliş tahmini üzerine USDC ile": "Buy with USDC based on Allora's bullish prediction",
  "satın al": "buy",
  "Allora'nın düşüş tahmini üzerine elimdeki": "Sell to USDC based on Allora's bearish prediction",
  "'leri USDC'ye çevir": "to USDC",
  "İşlem Önermiyor": "Does not recommend action",
  "30 saniyede bir güncelle": "update every 30 seconds",
  "Hedef Varlık:": "Target Asset:",
  "Güven:": "Confidence:",
  "Geliştirici Modu: Public Endpoint": "Developer Mode: Public Endpoint",
  "KLET Fiyatı": "KLET Price",
  "CÜZDAN BAĞLI": "WALLET CONNECTED",
  "BAĞLI DEĞİL": "NOT CONNECTED",
  "Sağlık Skoru": "Health Score",
  "LTV Oranı (Max %80)": "LTV Ratio (Max 80%)",
  "Likitasyon Riski! Lütfen teminat ekleyin veya borç ödeyin.": "Liquidation Risk! Please add collateral or repay debt.",
  "Teminatınız": "Your Collateral",
  "Kletia lending protokolüne elimdeki KLET ile teminat ekle": "Add collateral with my KLET to Kletia lending protocol",
  "Teminat Yönetimi": "Collateral Management",
  "Max Alınabilir:": "Max Borrowable:",
  "Kletia lending üzerinden USDC borç al": "Borrow USDC via Kletia lending",
  "Borç İşlemleri": "Borrowing Operations",
  "Hızlı Otonom İşlemler": "Fast Autonomous Operations",
  "Teminat Add": "Add Collateral",
  "Kletia lending protokolüne 50000 KLET teminat ekle": "Add 50000 KLET collateral to Kletia lending protocol",
  "Borç Al": "Borrow",
  "Kletia lending üzerinden 10 USDC borç al": "Borrow 10 USDC via Kletia lending",
  "Borç Öde": "Repay",
  "Kletia lending üzerindeki 10 USDC borcumu kapa": "Repay my 10 USDC debt on Kletia lending",
  "Teminat Çek": "Withdraw Collateral",
  "Kletia lending üzerinden 1000 KLET teminatımı geri çek": "Withdraw my 1000 KLET collateral via Kletia lending",
  "İsim en az 3 karakter olmalı": "Name must be at least 3 characters",
  "Webacy Taraması...": "Webacy Scan...",
  "Onay Pending...": "Pending Confirmation...",
  "Networkda İşleniyor...": "Processing on Network...",
  "Kayıt Success!": "Registration Success!",
  "Kayıt Ol": "Register",
  "Accountlanıyor...": "Calculating...",
  "Toplam Portföy Değeri": "Total Portfolio Value",
  "Gizle": "Hide",
  "Tümünü Gör": "See All",
  "LİKİT STAKİNG (LST)": "LIQUID STAKING (LST)",
  "Diğer DeFi Varlıkları": "Other DeFi Assets",
  "AKTİF DEFI POZİSYONLARI BÖLÜMÜ": "ACTIVE DEFI POSITIONS SECTION",
  "Borç:": "Debt:",
  "Sağlık (HF):": "Health (HF):",
  "Yatırılan:": "Supplied:",
  "Yatırılan USDC:": "Supplied USDC:",
  "Alınan Borç:": "Borrowed:",
  "Oy Gücü:": "Voting Power:",
  "Son İşlemler": "Recent Transactions",
  "Güvenlik Kontrolü...": "Security Check...",
  "Güvenli": "Safe",
  "Yüksek Riskli": "High Risk",
  "Kletia Omni-Engine hata yapabilir, lütfen işlemleri onaylarken son kez kontrol edin.": "Kletia Omni-Engine can make mistakes, please double check before confirming transactions.",
  "Base Modu Yakında": "Base Mode Coming Soon",
  "ARC MODE (Base Yakında)": "ARC MODE (Base Coming Soon)",
  "Ekosistem & Güvenlik": "Ecosystem & Security",
  "Webacy güvenlik merkezini aç": "Open Webacy security center",
  "Webacy Güvenlik Merkezi": "Webacy Security Center",
  "Allora yapay zeka merkezini aç": "Open Allora AI center",
  "Basename kayıt sistemini aç": "Open Basename registration system",
  "Airdrop simülatörünü aç": "Open Airdrop simulator",
  "Airdrop Simülatörü": "Airdrop Simulator",
  "x402 ödeme konsolunu aç": "Open x402 payment console",
  "Otonom Araçlar": "Autonomous Tools",
  "Balina takibi (copy-trade) başlat": "Start whale tracking (copy-trade)",
  "Otomatik getiri avcısı (yield optimizer) başlat": "Start auto yield optimizer",
  "Getiri Avcısı": "Yield Hunter",
  "Zamanlanmış / koşullu emir (limit order) başlat": "Start scheduled / conditional order (limit order)",
  "Yakında": "Soon",
  "Oturum Anahtarı": "Session Key",
  "Kletia Omni-Engine üzerinden 5 USDC'yi KLET ile swap et": "Swap 5 USDC to KLET via Kletia Omni-Engine",
  "Kletia staking kontratına 25 USDC kilitle": "Lock 25 USDC to Kletia staking contract",
  "Kletia Omni-Engine üzerinden 0xFf3a3CFC42D27E85DbA9Ea85f0bFEC34bd632f9A adresine 5 USDC toplu transfer yap": "Batch transfer 5 USDC to 0xFf... via Omni-Engine",
  "Kletia Omni-Engine üzerinden 0xFf3a3CFC42D27E85DbA9Ea85f0bFEC34bd632f9A adresine Kira Ödemesi notuyla 10 USDC memo transfer yap": "Send 10 USDC with Rent Payment memo to 0xFf... via Omni-Engine",
  "Kletia AI Agent'ı sisteme kaydet": "Register Kletia AI Agent to system",
  "Kletia havuzuna 100 USDC ve eşdeğer KLET likidite ekle": "Add 100 USDC and equivalent KLET liquidity to Kletia pool",
  "GEÇMİŞİ TEMİZLE": "CLEAR HISTORY",
  "Portföy verisi henüz çekilmedi. Sisteme <b>\"Portföyümü göster\"</b> yazarak güncel durumunu görebilirsin.": "Portfolio data not fetched yet. You can see your status by typing <b>\"Show my portfolio\"</b>.",
  "Yapay zeka ajanı başlatılıyor... X402 ödeme protokolü devrede.": "Starting AI agent... X402 payment protocol engaged.",
  "cüzdanı için gelişmiş sybil analizi yapmak istiyorum. Lütfen 'http://localhost:3001/api/premium/sybil-report?address=": "I want to do advanced sybil analysis for wallet. Please fetch Premium Sybil Analysis data by paying x402 to 'http://localhost:3001/api/premium/sybil-report?address=",
  "' adresinden X402 ödemesi yaparak Premium Sybil Analizi verisini al ve sonuçları (aktif günler, cüzdan yaşı, işlem varyansı) bana Türkçe olarak detaylıca açıkla.": "' and explain results (active days, wallet age, tx variance) to me in detail.",
  "Ajan ile bağlantı kurulamadı.": "Could not connect to agent.",
  "[SİSTEM]:": "[SYSTEM]:",
  "[ARAÇ ÇAĞRISI]: Ajan yetki araçlarını kullanıyor...": "[TOOL CALL]: Agent is using authorization tools...",
  "[SİSTEM HATASI]:": "[SYSTEM ERROR]:",
  "Lütfen geçerli bir 0x cüzdan adresi girin.": "Please enter a valid 0x wallet address.",
  "Düşük Risk": "Low Risk",
  "Yüksek Risk (Sybil)": "High Risk (Sybil)",
  "Düşük Risk (Organik)": "Low Risk (Organic)",
  "Çoklu API Veri Çekme Errorsı! Kletia Sunucularında ağ problemi yaşanıyor.": "Multiple API Fetch Error! Network issue on Kletia Servers.",
  "Kletia Süper Skor Formülü (%60 AI, %40 Gerçek Onchain Verisi)": "Kletia Super Score Formula (60% AI, 40% Real Onchain Data)",
  "Kletia Süper Skoru: TrustaLabs AI, Nomis, Coinbase SDK ve Blockscout verilerini tek potada eritir.": "Kletia Super Score: Merges TrustaLabs AI, Nomis, Coinbase SDK and Blockscout data.",
  "Analiz edilecek cüzdan adresini (0x...) girin": "Enter wallet address (0x...) to analyze",
  "API'lere Connectılıyor...": "Connecting to APIs...",
  "Süper Skoru Accountla": "Calculate Super Score",
  "Kletia Süper Skor": "Kletia Super Score",
  "%60 Yapay Zeka (AI) Repütasyonu, %40 Onchain Geçmişi kullanılarak hesaplanmıştır.": "Calculated using 60% AI Reputation and 40% Onchain History.",
  "Network İçi Ham Veri Analizi": "In-Network Raw Data Analysis",
  "Resmi Web3 Kimlik Çözücü": "Official Web3 Identity Resolver",
  "Base Name Sahibi": "Base Name Owner",
  "Tanımsız Wallet": "Unknown Wallet",
  "Net Gas Harcaması:": "Net Gas Spent:",
  "Onchain Ayak İzi": "Onchain Footprint",
  "Gün": "Days",
  "Wallet Yaşı": "Wallet Age",
  "Toplam İşlem": "Total Transactions",
  "Otonom X402 İşlemi Yürütülüyor...": "Autonomous X402 Process Running...",
  "🤖 AI Ajanı ile Derin Analiz (X402 Premium)": "🤖 Deep Analysis with AI Agent (X402 Premium)",
  "tarafından geliştirilmiş": "developed by",
  "AKTİF": "ACTIVE",
  "Akıllı Yatırım": "Smart Investment",
  "Arc vault kasama hemen 50 USDC aktar, faiz kazanmak istiyorum": "Transfer 50 USDC to my Arc vault immediately, I want to earn interest",
  "Notlu Ödeme": "Memo Payment",
  "Ahmetin cüzdanı olan 0xFf3a3CFC42D27E85DbA9Ea85f0bFEC34bd632f9A adresine kira ödemesi açıklamasıyla 10 USDC gönder": "Send 10 USDC to Ahmet's wallet 0xFf... with rent payment description",
  "Havuz Besleme": "Pool Funding",
  "Arc ağındaki Swap havuzuna 10 USDC likidite ekle": "Add 10 USDC liquidity to Swap pool on Arc network",
  "Esnek Kilit": "Flexible Lock",
  "Gelecek için Arc staking kontratına 25 USDC kilitle": "Lock 25 USDC to Arc staking contract for the future",
  "İzlenecek cüzdan adresini girin.": "Enter wallet address to track.",
  "🎯 Hedef (Balina) Walletı": "🎯 Target (Whale) Wallet",
  "💰 İşlem Başına Maksimum Limit (USDC)": "💰 Max Limit per Transaction (USDC)",
  "İzlemeyi Durdur": "Stop Tracking",
  "Otomatik Kopyalamayı Başlat": "Start Auto Copying",
  "Tarama yapmak istediğiniz akıllı kontrat veya cüzdan adresini girin, anında risk analizini görüntüleyin.": "Enter smart contract or wallet address to scan, view risk analysis instantly.",
  "RİSK": "RISK",
  "Akıllı Kontrat": "Smart Contract",
  "Wallet (EOA)": "Wallet (EOA)",
  "⚠️ UYARI: Kletia Otonom Ajanı ve Kletia Güvenlik Duvarı bu adresle herhangi bir işlem yapmanıza izin vermeyecektir.": "⚠️ WARNING: Kletia Autonomous Agent and Kletia Firewall will not allow any transaction with this address.",
  "modülü aktif edildi. İlgili arayüz aşağıda hazır:": "module activated. Relevant UI is ready below:",
  "Önce cüzdanını bağla.": "Connect your wallet first.",
  "Gateway kontratı deploy ediliyor...": "Deploying gateway contract...",
  "TX gönderildi:": "TX sent:",
  "TX onaylandı! Block:": "TX confirmed! Block:",
  "Kontrat oluşturuldu ama adres event'ten okunamadı.": "Contract created but address could not be read from event.",
  "Deploy hatası:": "Deploy error:",
  "Geçerli bir kontrat adresi girin.": "Enter a valid contract address.",
  "Kontrat yükleniyor:": "Loading contract:",
  "Kontrat yüklendi. Owner:": "Contract loaded. Owner:",
  "Kontrat yüklenemedi:": "Contract load failed:",
  "Wallet bağlı ve kontrat yüklü olmalı.": "Wallet must be connected and contract loaded.",
  "Wallet client bağlı değil.": "Wallet client not connected.",
  "x402 ödeme akışı başlatılıyor...": "x402 payment flow starting...",
  "İstek:": "Request:",
  "🎉 BAŞARILI! x402 ödemesi gerçekleşti ve veri alındı.": "🎉 SUCCESS! x402 payment processed and data received.",
  "Yanıt": "Response",
  "Ödeme hatası:": "Payment error:",
  "x402 debug bilgisi alınıyor...": "Fetching x402 debug info...",
  "Debug hatası:": "Debug error:",
  "Fiyat güncelleniyor:": "Updating price:",
  "Fiyat güncellendi:": "Price updated:",
  "Fiyat güncelleme hatası:": "Price update error:",
  "USDC çekim işlemi başlatılıyor...": "Starting USDC withdrawal...",
  "USDC başarıyla çekildi!": "USDC withdrawn successfully!",
  "Çekim hatası:": "Withdrawal error:",
  "Gateway URL kopyalandı.": "Gateway URL copied.",
  "Kontrat sıfırlandı.": "Contract reset.",
  "Test için boş kalabilir": "Can be left empty for test",
  "Kayıt İşlemi": "Registration",
  "Ajan Tarafından Onaylandı": "Approved by Agent",
  "Wallet": "Wallet",
  "Geliştirici Modu": "Developer Mode",
  "Ağ bağlantısı koptu": "Network disconnected",
  "Onaylı": "Approved",
  "Gözden Geçir": "Review",
  "Devre Dışı": "Disabled"
};

function processDirectory(directory) {
  const files = fs.readdirSync(directory);
  for (const file of files) {
    const fullPath = path.join(directory, file);
    if (fs.statSync(fullPath).isDirectory()) {
      processDirectory(fullPath);
    } else if (fullPath.endsWith('.ts') || fullPath.endsWith('.tsx')) {
      let content = fs.readFileSync(fullPath, 'utf8');
      let changed = false;
      for (const [tr, en] of Object.entries(replacements)) {
        if (content.includes(tr)) {
          content = content.split(tr).join(en);
          changed = true;
        }
      }
      if (changed) {
        fs.writeFileSync(fullPath, content, 'utf8');
        console.log('Translated:', fullPath);
      }
    }
  }
}

processDirectory(dir);
